<?php require 'auth.php'; require_once '../config/database.php';
$cats=$pdo->query('SELECT * FROM categories')->fetchAll(); $p=['id'=>'','category_id'=>'','name'=>'','slug'=>'','price'=>'','sale_price'=>'','image'=>'','hover_image'=>'','description'=>'','sizes'=>'S,M,L,XL','color'=>'','is_new'=>1,'is_sale'=>0];
if(!empty($_GET['id'])){ $st=$pdo->prepare('SELECT * FROM products WHERE id=?');$st->execute([$_GET['id']]);$p=$st->fetch(); }
if($_SERVER['REQUEST_METHOD']==='POST'){
$data=[$_POST['category_id'],$_POST['name'],$_POST['slug'],$_POST['price'],$_POST['sale_price']?:null,$_POST['image'],$_POST['hover_image'],$_POST['description'],$_POST['sizes'],$_POST['color'],isset($_POST['is_new'])?1:0,isset($_POST['is_sale'])?1:0];
if(!empty($_POST['id'])){ $data[]=$_POST['id']; $st=$pdo->prepare('UPDATE products SET category_id=?,name=?,slug=?,price=?,sale_price=?,image=?,hover_image=?,description=?,sizes=?,color=?,is_new=?,is_sale=? WHERE id=?'); $st->execute($data); }
else { $st=$pdo->prepare('INSERT INTO products(category_id,name,slug,price,sale_price,image,hover_image,description,sizes,color,is_new,is_sale) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)'); $st->execute($data); }
header('Location: index.php'); exit; }
?>
<!doctype html><html><head><meta charset="utf-8"><title>Sản phẩm</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><div class="form"><h1><?= $p['id']?'Sửa':'Thêm' ?> sản phẩm</h1><form method="post"><input type="hidden" name="id" value="<?=$p['id']?>"><select name="category_id"><?php foreach($cats as $c): ?><option value="<?=$c['id']?>" <?=$p['category_id']==$c['id']?'selected':''?>><?=$c['name']?></option><?php endforeach; ?></select><input name="name" required placeholder="Tên" value="<?=htmlspecialchars($p['name'])?>"><input name="slug" required placeholder="slug" value="<?=htmlspecialchars($p['slug'])?>"><input name="price" required type="number" placeholder="Giá" value="<?=$p['price']?>"><input name="sale_price" type="number" placeholder="Giá sale" value="<?=$p['sale_price']?>"><input name="image" required placeholder="Link ảnh chính" value="<?=htmlspecialchars($p['image'])?>"><input name="hover_image" placeholder="Link ảnh hover" value="<?=htmlspecialchars($p['hover_image'])?>"><input name="sizes" placeholder="S,M,L" value="<?=htmlspecialchars($p['sizes'])?>"><input name="color" placeholder="Màu" value="<?=htmlspecialchars($p['color'])?>"><textarea name="description" placeholder="Mô tả"><?=htmlspecialchars($p['description'])?></textarea><label><input type="checkbox" name="is_new" <?=$p['is_new']?'checked':''?>> Sản phẩm mới</label><br><label><input type="checkbox" name="is_sale" <?=$p['is_sale']?'checked':''?>> Sale</label><br><br><button class="btn">Lưu</button> <a href="index.php">Quay lại</a></form></div></body></html>
